### ISSUE TITLE
MJPEG doesn't update on Firefox

### ISSUE THREAD

**Issue by makew0rld** [donatj/imgboard#1]
Thanks for making this and sharing on HN! I understand it's just a demo project, but I'd be interested in finding out what the issue is here.

I'm on Firefox 80.0.1 on Linux, and the embedded MJPEG doesn't seem to reload on the HTML page. If I visit the `/image` page it works fine and reloads, but on the root the clicks go through but the image never updates.

**Comment by donatj** [comment]
MJPEG support on Firefox in mediocre. I believe when the form submits firefox preemptively kills the connection.

I'm not sure there's a lot I can do. I could sniff for firefox and make the response not be a 204 so the page actually refreshes, but I don't think it's worth it.

**Comment by donatj** [comment]
Beyond that I don't know that there's any hope in getting it fixed given the massive mozilla layoffs.

**Comment by bored-engineer** [comment]
@donatj Can you set the form's target to a small (hidden) iframe instead of the main window that way the primary window never sees a started navigation event?

**Comment by donatj** [comment]
Interesting idea, I'll give that a try
